name: Convert and Run Google Reviews Scraper

on:
  push:
    branches:
      - main  # Triggers the action on push to the main branch
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  convert-and-scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Set your preferred Python version

      - name: Install Jupyter and Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jupyter nbconvert
          pip install -r requirements.txt  # Ensure your dependencies like selenium and bs4 are listed here

      - name: Convert Jupyter Notebook to Python Script
        run: |
          jupyter nbconvert --to script reviews_scraping.ipynb
          mv reviews_scraping.py google_reviews_web_scraping.py

      # Install Chrome dependencies
      - name: Install Chrome
        run: |
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Run Google Reviews Scraper
        run: |
          python google_reviews_web_scraping.py  # Run the Python script converted from the notebook

      - name: Archive Output
        uses: actions/upload-artifact@v3
        with:
          name: reviews-output
          path: reviews_output.txt  # Upload the result file as an artifact
